[build]
  publish = "/"
  functions = "functions"

[build.environment]
  NODE_VERSION = "16.11.0"
  NPM_VERSION = "8.0.0"

[dev]
  framework = "#custom"
  command="gulp dev"
  targetPort = 1313
  port = 8888
  publish = "/"
  autoLaunch = true
